const SECTION_FIELDS = [
  // SG1 - ADMISSION
  // { name: "Strength", 
  //   key: "sg1_strength", 
  //   ratings: [
  //     { label: "98% - 100%", score: 5 }, 
  //     { label: "96% - 98%", score: 4 }, 
  //     { label: "94% - 96%", score: 3 }, 
  //     { label: "92% - 94%", score: 2 }, 
  //     { label: "90% - 92%", score: 1 },
  //     { label: "Not Applicable", score: 0 } ], 
  //   wf: 1 },
  { name: "Round 1", 
    key: "sg1_ug_round1", 
    ratings: [ 
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Round 2", 
    key: "sg1_ug_round2", 
    ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Round 3", 
    key: "sg1_ug_round3", 
    disableRating: true,
    ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Average Cutoff (Counseling)", 
    key: "sg1_cutoff_counseling", 
    ratings: [
      { label: "98% - 100%", score: 5 }, 
      { label: "96% - 98%", score: 4 }, 
      { label: "94% - 96%", score: 3 }, 
      { label: "92% - 94%", score: 2 }, 
      { label: "90% - 92%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Average Cutoff (Total Strength)", 
    key: "sg1_cutoff_total", 
    ratings: [
      { label: "98% - 100%", score: 5 }, 
      { label: "96% - 98%", score: 4 }, 
      { label: "94% - 96%", score: 3 }, 
      { label: "92% - 94%", score: 2 }, 
      { label: "90% - 92%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "PG Admission", 
    key: "sg1_pg", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "KVP Educational District", 
    key: "sg1_kvp", ratings: [
      { label: "95% - 100%", score: 5 }, 
      { label: "90% - 95%", score: 4 }, 
      { label: "85% - 90%", score: 3 }, 
      { label: "80% - 85%", score: 2 }, 
      { label: "75% - 80%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Districts Around KVP", 
    key: "sg1_around_kvp", ratings: [
      { label: "95% - 100%", score: 5 }, 
      { label: "90% - 95%", score: 4 }, 
      { label: "85% - 90%", score: 3 }, 
      { label: "80% - 85%", score: 2 }, 
      { label: "75% - 80%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Male Students", 
    key: "sg1_male", ratings: [
      { label: "95% - 100%", score: 5 }, 
      { label: "90% - 95%", score: 4 }, 
      { label: "85% - 90%", score: 3 }, 
      { label: "80% - 85%", score: 2 }, 
      { label: "75% - 80%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Female Students", 
    key: "sg1_female", ratings: [
      { label: "95% - 100%", score: 5 }, 
      { label: "90% - 95%", score: 4 }, 
      { label: "85% - 90%", score: 3 }, 
      { label: "80% - 85%", score: 2 }, 
      { label: "75% - 80%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  
  // SG2 - ACADEMIC ACHIEVEMENTS
  { name: "Without Backlog I Year", 
    key: "sg2_wo_backlog_i", 
    ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Without Backlog II Year", 
    key: "sg2_wo_backlog_ii", 
    ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Without Backlog III Year", 
    key: "sg2_wo_backlog_iii", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Without Backlog IV Year", 
    key: "sg2_wo_backlog_iv", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "With Backlog I Year", 
    key: "sg2_with_backlog_i", ratings: [
      { label: "95% - 100%", score: 5 }, 
      { label: "90% - 95%", score: 4 }, 
      { label: "85% - 90%", score: 3 }, 
      { label: "80% - 85%", score: 2 }, 
      { label: "75% - 80%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "With Backlog II Year", 
    key: "sg2_with_backlog_ii", ratings: [
      { label: "95% - 100%", score: 5 }, 
      { label: "90% - 95%", score: 4 }, 
      { label: "85% - 90%", score: 3 }, 
      { label: "80% - 85%", score: 2 }, 
      { label: "75% - 80%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "With Backlog III Year", 
    key: "sg2_with_backlog_iii", ratings: [
      { label: "95% - 100%", score: 5 }, 
      { label: "90% - 95%", score: 4 }, 
      { label: "85% - 90%", score: 3 }, 
      { label: "80% - 85%", score: 2 }, 
      { label: "75% - 80%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "With Backlog IV Year", 
    key: "sg2_with_backlog_iv", ratings: [
      { label: "100%", score: 5 }, 
      { label: "95% - 100%", score: 4 }, 
      { label: "90% - 95%", score: 3 },
      { label: "85% - 90%", score: 2 }, 
      { label: "Below 85%", score: 1 },
      { label: "Not Applicable", score: 0 } ],
    wf: 1 }, 
  { name: "CGPA - above 8.5", 
    key: "sg2_cgpa_1", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "CGPA 7.5 - 8.5", 
    key: "sg2_cgpa_2", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "CGPA 6.5 - 7.5", 
    key: "sg2_cgpa_3", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  
  // SG3 - STUDENTS POTENTIAL TRANSFORMATION
  { name: "Students Participation", 
    key: "sg3_participation", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Students Achievements", 
    key: "sg3_achievement", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Participation in other states/countries (Online mode)", 
    key: "sg3_online", ratings: [
     { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Participation in other states/other countries (Physical mode)", 
    key: "sg3_physical", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Technical contests like Hackathons/Ideathons", 
    key: "sg3_hackathon", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Achievements in contests like Hackathons", 
    key: "sg3_hackathon_achieve", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "SCI Indexed Journal (in Nos.)", 
    key: "sg3_sci", ratings: [
      { label: "1 No.", score: 5 },
      { label: "Not Applicable", score: 0 }, ], 
    wf: 1 },
  { name: "Scopus indexed publications / Patent Filing thro' product development (in Nos.)", 
    key: "sg3_scopus", ratings: [ 
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Journals, magazines, newsletters etc. published by the department (in Nos.)", 
    key: "sg3_journals", ratings: [
      { label: "3 Nos. & above", score: 5 }, 
      { label: "2 Nos.", score: 3 }, 
      { label: "1 No.", score: 1 },
      { label: "Not Applicable", score: 0 }, ], 
    wf: 1 },
  { name: "No. of projects (in %)", 
    key: "sg3_projects", ratings: [
      { label: "3 Nos.", score: 5 }, 
      { label: "2 Nos.", score: 3 }, 
      { label: "1 No.", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Worth of projects (5L internal + 5L external) (in Lakhs)", 
    key: "sg3_project_worth", ratings: [
      { label: "8L - 10L", score: 5 }, 
      { label: "6L - 8L", score: 4 }, 
      { label: "4L - 6L", score: 3 }, 
      { label: "2L - 4L", score: 2 }, 
      { label: "Less than 2L", score: 1 },
      { label: "Not Applicable", score: 0 } ],
    wf: 1 },
  { name: "Public sector undertakings & MNCs", 
    key: "sg3_mnc", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ],  
    wf: 1 },
  { name: "Other Private Industries", 
    key: "sg3_private", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Fellowship at NITs, IITs & IISC/Central universities & research institution",
    key: "sg3_fellowship", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 } ],
    wf: 1 },

  // SG4 - CAREER SETTLEMENT
  { name: "Through Placement Cell", 
    key: "sg4_placement", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 } ], 
    wf: 1 },
  { name: "Median Salary (in Lakhs)", 
    key: "sg4_median", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }],
    wf: 1 },
  { name: "Above 20 Lakhs (SD)", 
    key: "sg4_salary_1", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 },
      { label: "30%", score: 1 },
      { label: "Not Applicable", score: 0 } ], 
    wf: 1 },
  { name: "15-20 Lakhs (D1)", 
    key: "sg4_salary_2", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 },
      { label: "30%", score: 1 },
      { label: "Not Applicable", score: 0 } ], 
    wf: 1 },
  { name: "10-15 Lakhs (D2)", 
    key: "sg4_salary_3", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 },
      { label: "30%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "7-10 Lakhs", 
    key: "sg4_salary_4", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "5-7 Lakhs", 
    key: "sg4_salary_5", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "3.6-5 Lakhs", 
    key: "sg4_salary_6", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Below 3.6 Lakhs", 
    key: "sg4_salary_7", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Bring New Companies offering high salary packages", 
    key: "sg4_new_companies", ratings: [
     { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Conversion from Internships", 
    key: "sg4_internship_convert", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 } ],
    wf: 1 },
  { name: "Winning Contest/Hackathon", 
    key: "sg4_winning_contest", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Referral process through Alumni (in Nos.)", 
    key: "sg4_referral_alumni", ratings: [
      { label: "1 & Above", score: 5 }, 
      { label: "Not Applicable", score: 0 } ],
    wf: 1 },
  { name: "Showcasing through Social media (in Nos.)", 
    key: "sg4_social_media", ratings: [
      { label: "1 & Above", score: 5 }, 
      { label: "Not Applicable", score: 0 } ],
    wf: 1 },
  { name: "Through Foreign Languages studies", 
    key: "sg4_foreign_lang_studies", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 },
      { label: "Not Applicable", score: 0 } ],
    wf: 1 },
  { name: "GATE Exam (Only III year Students) obtain 30 score", 
    key: "sg4_gate", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "TOEFL, GRE, GMAT, IELTS, CAT, MAT etc.", 
    key: "sg4_ce_2", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Higher Education", 
    key: "sg4_higher_ed", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Foreign Universities (IELTS)", 
    key: "sg4_foreign_univ", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "IITs, NITs & IIMs (GATE & CAT)", 
    key: "sg4_iit", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Other institutions with NIRF Ranking up to 200 (Marine)", 
    key: "sg4_nirf_ranking", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Entrepreneurship", 
    key: "sg4_entrepreneurship", ratings: [
       { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }],  
    wf: 1 },
  { name: "Studying Foreign Languages (II & III year - Minimum level Certification)", 
    key: "sg4_foreign_lang", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }],
    wf: 1 },
  { name: "Studying Hindi Languages", 
    key: "sg4_hindi", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }],
    wf: 1 },
  { name: "PG Placement", 
    key: "sg4_pg_placement", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "PG Academic/Research Institution", 
    key: "sg4_research_inst", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  
  // SG5 - FACULTY MEMBERS
  { name: "Online Courses (NPTEL and other MOOC) - All Faculty", 
    key: "sg5_courses", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Attending FDP/STTP programs (Domain Specific only) - All Faculty", 
    key: "sg5_fdp", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Resource Persons in STTPs/FDPs", 
    key: "sg5_resource_persons", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "50% - 60%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Industry Know how - Industrial Visit (Asso. Prof. & Prof.)", 
    key: "sg5_ikh_visit", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Industry Know how - Industrial Training (AP with >2 yrs exp, AP(SG))", 
    key: "sg5_ikh_training", ratings: [
     { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Visit to R&D Organization/Reputed Institution (AP(SG), Asso. Prof., Prof.)", 
    key: "sg5_rd", ratings: [
     { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Fellowship (AP(SG), AP pursuing PhD, AP with PhD)", 
    key: "sg5_fellowship", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Training programs - With funding (FDP/STTP) (in Nos.)", 
    key: "sg5_training_fund", ratings: [
      { label: "1 No.", score: 5 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Training programs - Self supporting (in Nos.)", 
    key: "sg5_training_self", ratings: [
      { label: "1 No.", score: 5 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "International Webinars (Resource Person should be Foreigner) (in Nos.)", 
    key: "sg5_webinars", ratings: [
      { label: "1 No.", score: 5 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  
  // TEACHING LEARNING PROCESS
  { name: "E-Content development", 
    key: "sg5_econtent", ratings: [
      { label: "90% - 100%", score: 5 }, 
      { label: "80% - 90%", score: 4 }, 
      { label: "70% - 80%", score: 3 }, 
      { label: "60% - 70%", score: 2 }, 
      { label: "Less than 60%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ], 
    wf: 1 },
  { name: "Innovative TLP",
    key: "sg5_tlp", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }
    ],  
    wf: 1 },
  { name: "Value Added Courses", 
    key: "sg5_vac", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Memberships in Profession Societies at National/International Levels", 
    key: "sg5_memberships", ratings: [
      { label: "95% - 100%", score: 5 }, 
      { label: "90% - 95%", score: 4 }, 
      { label: "85% - 90%", score: 3 }, 
      { label: "80% - 85%", score: 2 }, 
      { label: "75% - 80%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Organizing school training programs", 
    key: "sg5_school_training", ratings: [
      { label: "100%", score: 5 }, 
      { label: "75%", score: 3 }, 
      { label: "50%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  
  // RESEARCH & DEVELOPMENT
  { name: "PhD holders", 
    key: "sg5_phd", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Supervisorship (All Ph.D. Holders)", 
    key: "sg5_phd_supervisor", ratings: [
      { label: "100%", score: 5 } ,
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "PhD Pursuing", 
    key: "sg5_phd_pursuing", ratings: [
      { label: "95% - 100%", score: 5 }, 
      { label: "90% - 95%", score: 4 }, 
      { label: "85% - 90%", score: 3 }, 
      { label: "80% - 85%", score: 2 }, 
      { label: "75% - 80%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Publications in SCI journals", 
    key: "sg5_sci", ratings: [
     { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Books/Book chapter authored (Scopus Indexed)", 
    key: "sg5_books", ratings: [
      { label: "100%", score: 5 }, 
      { label: "75%", score: 3 }, 
      { label: "50%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "No. of full time scholars (New Registration)", 
    key: "sg5_scholars", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Faculty Support - TRL8-TRL9 (All Prof. & Asso.Prof)", 
    key: "sg5_trl_high", ratings: [
     { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Faculty Support - TRL4-TRL7 (All AP(SG) and APs with PhDs)", 
    key: "sg5_trl_mid", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Faculty Support - TRL1-TRL4 (All APs)", 
    key: "sg5_trl_low", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Revenue generated from Granted Patents (in Lakhs)", 
    key: "sg5_patent_revenue", ratings: [
      { label: "1L+", score: 5 }, 
      { label: "0.8L-1L", score: 4 }, 
      { label: "0.6L-0.8L", score: 3 }, 
      { label: "0.4L-0.6L", score: 2 }, 
      { label: "Below 0.4L", score: 1 }], 
    wf: 1 },
  { name: "Consultancy", 
    key: "sg5_consultancy", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Worth of Consultancy (in Lakhs)", 
    key: "sg5_consultancy_worth", ratings: [
      { label: "4L+", score: 5 }, 
      { label: "3L+", score: 4 }, 
      { label: "2L+", score: 3 }, 
      { label: "1L+", score: 2 }, 
      { label: "Below 1L", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "No. of Project Proposals to funding Agency", 
    key: "sg5_project_proposal", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Worth of On-going projects (in Crores)", 
    key: "sg5_project_worth", ratings: [
      { label: "25L+", score: 5 }, 
      { label: "20L - 25L", score: 4 }, 
      { label: "15L - 20L", score: 3 }, 
      { label: "10L - 15L", score: 2 }, 
      { label: "Below 10L", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Institution Seed Money (in Lakhs)", 
    key: "sg5_seed_money", ratings: [
      { label: "2L+", score: 5 }, 
      { label: "1.5L - 2L", score: 4 }, 
      { label: "1L - 1.5L", score: 3 }, 
      { label: "0.5L - 1L", score: 2 }, 
      { label: "Below 0.5L", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "No. of. Special Lab/ Centre of Excellence/research facility/ Technobation centre/Industry collaborated labs (in Nos.)", 
    key: "sg5_lab", ratings: [
      { label: "1 No.", score: 5 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "No. of functional MoUs", 
    key: "sg5_mou", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "MoUs signed in the year", 
    key: "sg5_mou_signed", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "No. of Activities through MoUs", 
    key: "sg5_mou_activities", ratings: [
      { label: "80% - 100%", score: 5 }, 
      { label: "60% - 80%", score: 4 }, 
      { label: "40% - 60%", score: 3 }, 
      { label: "20% - 40%", score: 2 }, 
      { label: "Less than 20%", score: 1 },
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },

  // SG6 - OUTREACH PROGRAMMES
  { name: "International Events held at foreign countries (in Nos.)", 
    key: "sg6_international_event", ratings: [
      { label: "1 No. & above", score: 5 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "National Events", 
    key: "sg6_national_lecture", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "International collaboration (Publication, book, Project submission, etc.) (in Nos.)", 
    key: "sg6_international_colab", ratings: [
      { label: "1 No. & above", score: 5 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Inter-institutional collaboration (Publication, book, Project submission, etc.) (in Nos.)", 
    key: "sg6_institutional_collab", ratings: [
      { label: "1 No. & above", score: 5 }, 
      { label: "Not Applicable", score: 0 }],   
    wf: 1 },
  { name: "Awards/Recognitions received on research, innovations, and outstanding performance (in Nos.)", 
    key: "sg6_awards", ratings: [
      { label: "1 No. & above", score: 5 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Foreign country visited for collaborative work (in Nos.)", 
    key: "sg6_foreign_visit", ratings: [
      { label: "1 No. & above", score: 5 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Social Related activities",
    key: "sg6_social_activities", ratings: [
      { label: "100%", score: 5 }, 
      { label: "50%", score: 3 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
  { name: "Training to Industry personnel (in Nos.)", 
    key: "sg6_industry_training", ratings: [
      { label: "1 No. & above", score: 5 }, 
      { label: "Not Applicable", score: 0 }], 
    wf: 1 },
];

//   // SG7 - EXTENSION ACTIVITIES
//   { name: "Alumni meets", 
//     key: "sg7_alumni_meets", ratings: [
//       { label: "2+", score: 5 }, 
//       { label: "1", score: 3 }], 
//     wf: 1 },
//   { name: "Fund raising (in Lakhs)", 
//     key: "sg7_fund_raising", ratings: [
//       { label: "10L+", score: 5 }, 
//       { label: "8L-10L", score: 4 }, 
//       { label: "6L-8L", score: 3 }, 
//       { label: "4L-6L", score: 2 }, 
//       { label: "Below 4L", score: 1 }], 
//     wf: 1 },
//   { name: "No. of Activities - Extracurricular Activities", 
//     key: "sg7_extracurricular", ratings: [
//       { label: "10+/club", score: 5 }, 
//       { label: "8-10/club", score: 4 }, 
//       { label: "6-8/club", score: 3 }, 
//       { label: "4-6/club", score: 2 }, 
//       { label: "Below 4/club", score: 1 }], 
//     wf: 1 },
//   { name: "No. of Activities - Co-curricular Activities", 
//     key: "sg7_cocurricular", ratings: [
//       { label: "10+/club", score: 5 }, 
//       { label: "8-10/club", score: 4 }, 
//       { label: "6-8/club", score: 3 }, 
//       { label: "4-6/club", score: 2 }, 
//       { label: "Below 4/club", score: 1 }], 
//     wf: 1 },
//   { name: "Achievements - Extracurricular Activities from govt/recognized bodies", 
//     key: "sg7_extracurricular_achieve", ratings: [
//       { label: "1+/club", score: 5 }, 
//       { label: "1/club", score: 4 }, 
//       { label: "None", score: 2 }], 
//     wf: 1 },
//   { name: "Achievements - Co-curricular Activities from govt/recognized bodies", 
//     key: "sg7_cocurricular_achieve", ratings: [
//       { label: "1+/club", score: 5 }, 
//       { label: "1/club", score: 4 }, 
//       { label: "None", score: 2 }], 
//     wf: 1 },
//   { name: "Activities for promotion of universal values, national values, human values", 
//     key: "sg7_universal_values", ratings: [
//       { label: "2 out of 10+/club", score: 5 }, 
//       { label: "2 out of 10/club", score: 4 }, 
//       { label: "1 out of 10/club", score: 3 }, 
//       { label: "Less than 1", score: 2 }], 
//     wf: 1 },
//   { name: "National festivals and Anniversaries of great Indian personalities", 
//     key: "sg7_national_festivals", ratings: [
//       { label: "3 out of 10+/club", score: 5 }, 
//       { label: "3 out of 10/club", score: 4 }, 
//       { label: "2 out of 10/club", score: 3 }, 
//       { label: "1 out of 10/club", score: 2 }, 
//       { label: "Less than 1", score: 1 }], 
//     wf: 1 },
//   { name: "Sports events organized (District/Zonal/National Level)", 
//     key: "sg7_sports_events", ratings: [
//       { label: "5+/5+/5+", score: 5 }, 
//       { label: "5/5/5", score: 4 }, 
//       { label: "4/4/4", score: 3 }, 
//       { label: "3/3/3", score: 2 }, 
//       { label: "Below 3/3/3", score: 1 }], 
//     wf: 1 },
//   { name: "No. of medals won (District/Zonal/National Level)", 
//     key: "sg7_medals", ratings: [
//       { label: "5+/5+/5+", score: 5 }, 
//       { label: "5/5/5", score: 4 }, 
//       { label: "4/4/4", score: 3 }, 
//       { label: "3/3/3", score: 2 }, 
//       { label: "Below 3/3/3", score: 1 }], 
//     wf: 1 },

//   // SG8 - INSTITUTIONAL RECOGNITION
//   { name: "NIRF Ranking", 
//     key: "sg8_nirf", ratings: [
//       { label: "Within 150", score: 5 }, 
//       { label: "Within 200", score: 4 }, 
//       { label: "Within 250", score: 3 }, 
//       { label: "Within 300", score: 2 }], 
//     wf: 1 },
//   { name: "NIRF-Innovation", 
//     key: "sg8_nirf_innovation", ratings: [
//       { label: "Within 50", score: 5 }, 
//       { label: "Within 100", score: 4 }, 
//       { label: "Within 150", score: 3 }], 
//     wf: 1 },
//   { name: "NBA", 
//     key: "sg8_nba", ratings: [
//       { label: "Full Accreditation", score: 5 }, 
//       { label: "Partial", score: 3 }], 
//     wf: 1 },
//   { name: "NAAC", 
//     key: "sg8_naac", ratings: [
//       { label: "A++", score: 5 }, 
//       { label: "A+", score: 4 }, 
//       { label: "A", score: 3 }], 
//     wf: 1 },
//   { name: "AICTE-CII Survey (Dept. Level)", 
//     key: "sg8_aicte_cii", ratings: [
//       { label: "Platinum", score: 5 }, 
//       { label: "Gold", score: 4 }, 
//       { label: "Silver", score: 3 }], 
//     wf: 1 },
// ];

